"""
will_template.py — ReportLab PDF generator for the Last Will & Testament document.
"""
import io
from datetime import datetime, timezone
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, KeepTogether,
)

# ── Palette ──────────────────────────────────────────────────────────────────
BRAND  = colors.HexColor("#c4622d")
DARK   = colors.HexColor("#1a1a1a")
GRAY   = colors.HexColor("#6b7280")
LIGHT  = colors.HexColor("#f3f4f6")
BORDER = colors.HexColor("#d1d5db")


def _build_styles():
    s = getSampleStyleSheet()
    s.add(ParagraphStyle("WillTitle",   fontName="Helvetica-Bold",    fontSize=20, textColor=DARK,  spaceAfter=4, alignment=1))
    s.add(ParagraphStyle("WillSubtitle",fontName="Helvetica",         fontSize=11, textColor=GRAY,  spaceAfter=16, alignment=1))
    s.add(ParagraphStyle("SectionHead", fontName="Helvetica-Bold",    fontSize=11, textColor=BRAND, spaceAfter=6, spaceBefore=16, borderPad=4))
    s.add(ParagraphStyle("Body",        fontName="Helvetica",         fontSize=10, textColor=DARK,  spaceAfter=6, leading=15))
    s.add(ParagraphStyle("BodyBold",    fontName="Helvetica-Bold",    fontSize=10, textColor=DARK,  spaceAfter=6))
    s.add(ParagraphStyle("SmallNote",   fontName="Helvetica-Oblique", fontSize=8,  textColor=GRAY,  spaceAfter=4))
    s.add(ParagraphStyle("Footer",      fontName="Helvetica-Oblique", fontSize=8,  textColor=GRAY,  spaceAfter=4, alignment=1))
    s.add(ParagraphStyle("SignLabel",   fontName="Helvetica-Bold",    fontSize=9,  textColor=GRAY,  spaceAfter=2))
    return s


def generate_will_pdf(
    profile: dict,
    assets: list[dict],
    mappings: list[dict],
    beneficiaries: list[dict],
    executor_name: str = "",
    special_instructions: str = "",
    witness_1_name: str = "",
    witness_2_name: str = "",
) -> bytes:
    """
    Generate the Last Will & Testament PDF using Gemini AI and return raw bytes.
    """
    from services.gemini_service import generate_will_text
    import re
    
    will_text = generate_will_text(
        profile, assets, mappings, beneficiaries, 
        executor_name, special_instructions, witness_1_name, witness_2_name
    )

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        topMargin=2 * cm, bottomMargin=2.5 * cm,
        leftMargin=2.5 * cm, rightMargin=2.5 * cm,
    )
    styles = _build_styles()
    story = []

    today = datetime.now(timezone.utc).strftime("%d %B %Y")
    
    # Optional branding at the top
    story.append(Paragraph("LAST WILL AND TESTAMENT", styles["WillTitle"]))
    story.append(HRFlowable(width="100%", thickness=1.5, color=BRAND, spaceAfter=28))

    for line in will_text.split('\n'):
        line = line.strip()
        if not line:
            story.append(Spacer(1, 0.3 * cm))
            continue
            
        # Parse bold text
        line = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', line)
        story.append(Paragraph(line, styles["Body"]))
        
    # Legal Footer
    story.append(Spacer(1, 1 * cm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=BORDER, spaceAfter=8))
    
    testator_name = profile.get("full_name") or "Unknown"
    story.append(Paragraph(
        f"This document constitutes the Last Will and Testament of {testator_name}. "
        "It was generated by Paradosis Vault and must be executed, witnessed, and stored "
        "in accordance with the applicable laws of the jurisdiction. "
        "This document requires original signatures to be legally valid. "
        f"Document generated on {today}.",
        styles["Footer"],
    ))

    doc.build(story)
    buf.seek(0)
    return buf.read()
